const mapeamentoCampos = {
    nome: "Nome",
    cota: "Cota",
    situacao: "Situação",
    matricula: "Matrícula",
    codigo: "Código",
    ch: "Carga horária",
    coordenador: "Coordenador",
    descricao: "Descrição",
    diretoria: "Diretoria",
    eixo: "Eixo",
    modalidade: "Modalidade",
    resolucao_criacao: "Resolução criação",
    cep: "CEP",
    cnpj: "CNPJ",
    endereco: "Endereço",
    telefone: "Telefone",
    sigla: "Sigla",
    estado_conservacao: "Estado de conservação",
    numero: "Número",
    valor_inicial: "Valor inicial (R$)",
    valor_liquido_contabil: "Valor líquido contábil (R$)",
    jornada_trabalho: "Jornada de trabalho",
    cargo_emprego: "Cargo / Emprego",
    disciplina_ingresso: "Disciplina Ingresso",
    funcao_codigo: "Código da função",
    is_siape: "É SIAPE",
    total_servidores: "Total de servidores",
    aprovado: "Aprovado",
    area_conhecimento: "Área / conhecimento",
    foco_tecnologico: "Foco tecnológico",
    inicio_execucao: "Início da execução",
    fim_execucao: "Fim da execução",
    justificativa: "Justificativa",
    resumo: "Resumo",
    resultados_esperados: "Resultados esperados",
    valor_total_executado: "Valor total executado (R$)",
    titulo: "Título",
    aluno: "Aluno",
    valor_bolsa: "Valor da bolsa (R$)",
    categoria_bolsa: "Categoria da bolsa",
    setor: "Setor",
    curso: "Curso",
    campus: "Campus",
    unidade_organizacional: "Unidade organizacional",
    superior: "Superior",
    matrizes: "Matrizes",
    natureza_participacao: "Natureza participação",
    municipio: "Município",
    uo: "Unidade organizacional",
    setor_exercicio: "Setor de exercício",
    lotacao_siap: "Lotação SIAP",
    lotacao_suap: "Lotação SUAP",
    setores_filho: "Setores filhos",
    author: "Autor",
    project: "Projeto",
    participantes: "Participantes"
}
export const retornarNomeDosCamposDosDadosCorretamente = (valor) => {
    return mapeamentoCampos[valor] || valor;
};

